var NATIONAL_PARKS = {
    "alaska": ["Denali", "Gates of the Arctic", "Glacier Bay", "Katmai", "Kenai Fjords", "Kobuk Valley", "Lake Clark", "Wrangell - St. Elias"],
    "american samoa": ["American Samoa"],
    "arizona": ["Grand Canyon", "Petrified Forest", "Saquaro"],
    "arkansas": ["Hot Springs"],
    "california": ["Channel Islands", "Death Valley", "Joshua Tree", "Kings Canyon", "Lassen Volcanic", "Redwood", "Sequoia", "Yosemite"],
    "colorado": ["Black Canyon of the Gunnison", "reat Sand Dunes", "Mesa Verde", "Rocky Mountain"],
    "florida": ["Biscayne", "Dry Tortugas", "Everglades"],
    "hawaii": ["Haleakala", "Hawaii Volcanoes"],
    "idaho": ["Yellowstone"],
    "kentucky": ["Mammoth Cave"],
    "maine": ["Acadia"],
    "michigan": ["Isle Royale"],
    "minnesota": ["Voyageurs"],
    "montana": ["Glacier", "Yellowstone"],
    "nevada": ["Great Basin"],
    "new mexico": ["Carlsbad Caverns"],
    "north carolina": ["Great Smoky Mountains"],
    "north dakota": ["Theodore Roosevelt"],
    "ohio": ["Cuyahoga Valley"],
    "oregon": ["Crater Lake"],
    "south sarolina": ["Congaree"],
    "south dakota": ["Badlands", "Wind Cave"],
    "tennessee": ["Great Smoky Mountains"],
    "texas": ["Big Bend", "Guadalupe Mountains"],
    "u s virgin islands": ["Virgin Islands"],
    "utah": ["Arches", "Bryce Canyon", "Capitol Reef", "Canyonlands", "Zion"],
    "virginia": ["Shenandoah"],
    "washington": ["Mount Rainier", "North Cascades", "Olympic"],
    "wyoming": ["Grand Teton", "Yellowstone"]
};